# Info about you
name: Shirobokova Margarita
position: Data Scientist
email: mail.com
company_name: 
company_url: 
place_name: Moscow

# Blog info
title: Brendan Hasz
description: Blog
url: http://brendanhasz.github.io/

# Social links
github_url: 
linkedin_url: 
publications_url: 
social:
  links:
    - https://github.com/

# Images + files
logo: /assets/img/headshot.png
cv_url: /assets/files/BrendanHasz_CV.pdf
resume_url: /assets/files/BrendanHasz_Resume.pdf

# Blog settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
highlighter: rouge
color_mode: auto  # auto, light, or dark
comments: true
disqus_shortname: brendanhasz-github-io
syntax_highlight_stylesheet: syntax_highlight.css

# Colors - light mode
colors:
  text: 282828
  tag: dbefdc
  tag_hover: 93cf95
  header_background: 2b422b
  header_text: dbefdc
  header_link_hover: 93cf95
  links: 459c48
  links_visited: 357a38

# Colors - dark mode
colors_dark:
  background: 333
  text: ccc
  tag: 2e6830
  tag_hover: 93cf95
  header_background: 232
  header_text: 93cf95
  header_link: 93cf95
  header_link_hover: 459c48
  links: 459c48
  links_visited: 357a38
